/**
 * Created by Александр on 25.12.2017.
 */

export const ADD_TO_PLAYLIST               = 'ADD_TO_PLAYLIST';
export const SET_PLAYLIST_INDICATOR        = 'SET_PLAYLIST_INDICATOR';
export const REMOVE_SONG_FROM_PLAYLIST_ONE = 'REMOVE_SONG_FROM_PLAYLIST_ONE';
export const REMOVE_SONG_FROM_PLAYLIST_TWO = 'REMOVE_SONG_FROM_PLAYLIST_TWO';
